training_arguments:
  warmup_steps: 100
  gradient_accumulation_steps: 4
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  evaluation_strategy: 'steps'
  eval_steps: 1000
  save_steps: 1000
  metric_for_best_model: 'f1'
  greater_is_better: True
  learning_rate: 1.0e-4
  remove_unused_columns: False
  report_to: 'wandb'
  load_best_model_at_end: True
  group_by_length: True
  save_total_limit: 3